### ISSUE TITLE
有一个图标遇到问题

### ISSUE THREAD

**Issue by cz848** [thunkli/panda#6]
![image](https://user-images.githubusercontent.com/369481/29745900-710cd5d4-8afa-11e7-817b-4579f195cf8e.png)
这个是原始图标，是单个复合路径，然后生成字体之后出问题了。
![image](https://user-images.githubusercontent.com/369481/29745915-c488f99a-8afa-11e7-883c-9d85e907c8ab.png)
 把手被填实了。。。

**Comment by thunkli** [comment]
@cz848 svg格式的图标发我，我试一下

**Comment by cz848** [comment]
[coffee.svg.zip](https://github.com/thunkli/panda/files/1254216/coffee.svg.zip)

**Comment by thunkli** [comment]
[coffee.svg 2.zip](https://github.com/thunkli/panda/files/1254232/coffee.svg.2.zip)
把手要用路径修改器 而不是 建立复合路径

**Comment by cz848** [comment]
谢谢，果然好了，原来以为建立复合路径能省体积，所以全部组合到一起了。
